<%@ page language="java" contentType="text/html;charset=UTF-8"%>	
<div class="box">
						<input id='kw' type="text"  placeholder="请输入搜索内容" onfocus="clearinput()" onblur="set_search_input()" class='search_on_web' style="width: 180px; border: 1px solid #1e90ff;height: 30px;float: left;padding:0 0 0 40px;">
						<div><input type="submit" value="搜索" style="width: 65px;height: 32px;float: right;margin-right: 40px;background: #1e90ff;color: white;text-align: center;line-height: 32px;cursor: pointer;font-size:18px"></div>
</div>